In [1]:
#write a program to create a simple 1D array
import numpy as n
a=n.array([1,5,3])
b=n.array([1,5,3])
print(a.dot(b))

35


In [2]:
#write a program to create a simple 2D array
a=n.array([[1,5,3],[2,6,5]])
print(a.transpose())
b=a.transpose()
a.ndim
b.shape

[[1 2]
 [5 6]
 [3 5]]


(3, 2)

In [3]:
#write a program to create a simple 3D array
a=n.array([[[1,5],[2,6]],[[1,2],[1,3]]])
print(a)
a.ndim
a.shape

[[[1 5]
  [2 6]]

 [[1 2]
  [1 3]]]


(2, 2, 2)

In [4]:
#write a program mathematic operation in array
a=n.array([[1,2],[3,4]])
b=n.array([[5,6],[7,8]])
add=a+b
sub=a-b
mul=n.matmul(a,b)
div=a/b
print(f'sum: {add}\nsub: {sub}\nmul: {mul}\ndiv: {div}')

sum: [[ 6  8]
 [10 12]]
sub: [[-4 -4]
 [-4 -4]]
mul: [[19 22]
 [43 50]]
div: [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [5]:
#write a program to print a array range between 1 to 40 and show 7 int random numbers
import random
a=[]
for i in range(7):
    x=random.randrange(1,40)
    a.append(x)
b=n.array(a)
print(b)

[28 27 16 23 19 18 33]


In [6]:
x=[i for i in range(1,40,7)]
a=n.array(x)
print(a)

[ 1  8 15 22 29 36]


In [7]:
a=n.random.randint(1,40,7)
print(a)

[39 17 31 21 13 39 17]


In [8]:
a=n.array([[1,2],[3,4]])
b=n.array([[5,6],[7,8]])
print(n.multiply(a,b))

[[ 5 12]
 [21 32]]


In [9]:
n.__version__

'1.21.5'

In [10]:
a=n.array([[1,2],[3,4]])
b=n.array([[5,6],[7,8]])
print(n.multiply(a,b))

[[ 5 12]
 [21 32]]


In [11]:
#write a program to set dimension of an array to 5
a=n.array([1,2,3],ndmin=5)
print(a)
a.ndim

[[[[[1 2 3]]]]]


5

In [12]:
a=n.array([[1,2,3],[4,5,6]])
print(a[1,2])

6


In [13]:
#arrange function
a=n.arange(0,10,1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
#program to print all even and odd numbers 50 to 100
a=n.arange(50,101,2)
print(a)
a=n.arange(51,100,2)
print(a)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]
[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


In [15]:
#print all number to 1 t0 2
a=n.arange(1,2,.1)
print(a)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [16]:
#create array with full zeros
b=n.zeros((2,2),dtype=int)
print(b)

[[0 0]
 [0 0]]


In [17]:
#create array with full ones
b=n.ones((2,2),dtype=int)
print(b)

[[1 1]
 [1 1]]


In [18]:
#write a program to add 9 to a zero matrix
b=n.ones((2,2),dtype=int)
print(f'{b+9}\n{b-9}\n{b/9}\n')

[[10 10]
 [10 10]]
[[-8 -8]
 [-8 -8]]
[[0.11111111 0.11111111]
 [0.11111111 0.11111111]]



In [19]:
#to craete 2d array which contains values 1,2,3,4,5,6
#acces 5 from this array and store to variable
#using that variable update the matrix by using scalar addition,multi,sub,div
a=n.array([[1,2,3],[4,5,6]])
print(a)
b=a[1,1]
print(f'add:={a+b}\nsub={a-b}\nmul={a*b}\ndiv={a/b}')

[[1 2 3]
 [4 5 6]]
add:=[[ 6  7  8]
 [ 9 10 11]]
sub=[[-4 -3 -2]
 [-1  0  1]]
mul=[[ 5 10 15]
 [20 25 30]]
div=[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [20]:
a=n.array([[[1,2,3]],[[2,3,6]]])
print(a[1,0,1:])

[3 6]


In [21]:
a=n.array([[[1,2,3]],[[3,4,5]],[[5,6,7]]])
a.shape
print(a[2,0,:2])

[5 6]


In [22]:
a=n.array([1],dtype='int32')
a.dtype

dtype('int32')

In [23]:
x=n.array([[1,2],[2,3]],ndmin=5)
#to acces 3 from the array
x[0,0,0,1,1]
#write a prgrm to convert 1d to 2d
a=n.array([2],ndmin=2)
#write a prgrm to convert 1d to 2*3
b=n.array([1,2,3,4,5,6])
b.reshape(2,3)
#create a values of array ranging from 2to10 and acces 7 from it
a=n.array([2,3,4,5,6,7,8,9,10])
a[5]

7

In [24]:
b=n.array([1,2,3,4,5,6])
b.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [25]:
b=n.array([[[1,2,3]],[[2,3,5]],[[4,5,7]]])
b[2,0,1:]

array([5, 7])

In [26]:
#write a program read values from 1 to 20 and create a 1d array using the values and re shape it to 3d
a=n.arange(1,21)
print(a)
b=a.reshape(10,2,1)
print(b)
b[5,0,0]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]

 [[17]
  [18]]

 [[19]
  [20]]]


11

In [27]:
a=n.array([[[1,2]]])
a.reshape(-1,2)

array([[1, 2]])

In [28]:
a=n.array([True,False])
a.dtype
b=n.array(['g','g'],dtype='S')
b.dtype
c=n.array([3,8],dtype='F')#TO COMPLEX
c.dtype
d=n.array([3,8],dtype='f')# to float
d.dtype
e=n.array([3.4,8.7],dtype='i')# to int
e.dtype

dtype('int32')

In [29]:
a=n.array([[1,2,3],[3,4,5]])
for 

SyntaxError: invalid syntax (4115320452.py, line 2)

In [ ]:
#replacing array iteams
a=n.array([[1,2,3],[3,4,5]])
b=n.array([[1,2,3],[3,4,5]])
c=n.array([[1,2,3],[3,4,5]])
d=n.array([[[1,2,3]],[[3,4,5]]])#3D
d[1,0,0]=9
c[1,::2]=6 #using step
a[1:]=1
b[1,0]=6
print(a)
print(b)
print(c)
print(d)

In [ ]:
# iterate through array
a=n.array([[1,2,3],[3,4,5]])
for i in n.nditer(a):
    print(i)
a=n.array([[[1,2,3]],[[3,4,5]]])
for j in n.nditer(a):
    print(j)

In [ ]:
#print element and their positon element
a=[1,2,3]
for i in enumerate(a):
    print(i)

In [ ]:
a=n.array([[1,2,3],[3,4,5]])
for i in n.ndenumerate(a):
    print(i)
    
a=n.array([[[1,2,3]],[[3,4,5]]])
for i in n.ndenumerate(a):
    print(i)

In [ ]:
# #numpy array joining
a=n.array([1,2,3])
b=n.array([6,7,8])
n.concatenate((a,b))
          
#2d joining
a=n.array([[1,2,3],[3,4,5]])
b=n.array([[6,7,8],[8,9,10]])
n.concatenate((a,b))

#3d joining
a=n.array([[[1,2,3]],[[3,4,5]]])
b=n.array([[[6,7,8]],[[8,9,10]]])
n.concatenate((a,b),axis=1)

#based on axis
a=n.array([[[1,2,3]]])
b=n.array([[[6,7,8]]])
n.concatenate((a,b),axis=1)

a=n.array([[[1,2]],[[3,4]],[[5,6]]])
b=n.array([[[11,22]],[[33,44]],[[55,66]]])
c=n.concatenate((a,b),axis=1)
print('axis 1:\n',c)
#axis 2
a=n.array([[[1,2]],[[3,4]],[[5,6]]])
b=n.array([[[11,22]],[[33,44]],[[55,66]]])
d=n.concatenate((a,b),axis=2)
print('axis 2:\n',d)
#axis 3
a=n.array([[[[1,2]],[[3,4]],[[5,6]]]])
b=n.array([[[[11,22]],[[33,44]],[[55,66]]]])
e=n.concatenate((a,b),axis=3)
print('axis 3:\n',e)

In [ ]:
#write a program to create a 2d array with one on the boarder and zero inside
# b=n.ones((3,4),dtype=int)
# b[1,1:3]=0
# print(b)
c=n.zeros((3,4),dtype=int)
c[::2,:]=1
c[1,::3]=1
# c[2,0:]=1
print(c)

In [ ]:
#write a numpy program to 8*8 matrix and fill it with check board pattern
b=n.ones((8,8),dtype=int)
b[::2,::2]=0
b[1::2,1::2]=0
print(b)

In [ ]:
b=n.zeros((8,8),dtype=int)
b[::2,::2]=1
b[1::2,1::2]=1
print(b)

In [ ]:
#write a numpy program to 8*8 matrix of 9 and fill it with 6 with alternate value
b=n.full((8,8),9)# to create matrix
b[::2,::2]=6
b[1::2,1::2]=6
print(b)

In [ ]:
a=n.zeros((9,9),dtype=int)
a[1:-1,1:-1]=1
a[2:-2,2:-2]=2
a[3:-3,3:-3]=3
a[4,4]=4
print(a)

In [ ]:
a=n.ones((5,5),dtype=int)
a[1:-1,1:-1]=2
a[2,2]=8
a

In [ ]:
a=n.ones((3,5),dtype=int)
a[::2,1::2]=0
b=[i for i in range(5)]
a[1]=b
a

In [ ]:
a=n.arange(2,19,2)
a.reshape(3,3)

In [ ]:
a=n.arange(2,19,2)
b=a.reshape(3,3)
b.T

In [ ]:
#copying an array
a=n.array([1,2,3])
b=a.copy()
b[1]=10
b

In [ ]:
#copying suitable elements using slicing
a=n.array([[[1,2]],[[3,4]],[[5,6]]])
b=n.copy(a[1,0,0])
b

In [ ]:
#stacking
a=n.array([1,2,3])
b=n.array([3,4,5])
n.stack((a,b))

a=n.array([[1,2,3],[2,3,4]])
b=n.array([[4,5,6],[6,7,8]])
n.stack((a,b))

a=n.arange(1,7)
c=a.reshape(2,3)
b=n.arange(8,14)
e=b.reshape(2,3)
n.stack((c,e))

a=n.array([[1,2,3],[4,5,6]])
b=n.array([[11,12,31],[41,51,61]])
c=n.stack((a,b))
#print(c)

a=n.array([[1,2,3],[4,5,6]])
b=n.array([[11,21,31],[41,51,16]])
e=n.stack((a,b),axis=1)
#print(e)

a=n.array([[[1,2,3]],[[4,5,6]]])
print(a)
b=n.array([[[11,21,31]],[[41,51,16]]])
print(b)
print('axis=0:',n.stack((a,b))) #combine 2 arrays and to 4D
print('axis=1:',n.stack((a,b),axis=1)) #combine first row of 2 array as 2D and whole into 4D
print('axis=2:',n.stack((a,b),axis=2)) #combine first row of 2 array as 1D and whole into 4D
print('axis=3:',n.stack((a,b),axis=3)) #combine 1st coloums as 1D and whole 4D

In [ ]:
a=n.array([[[1,2,3]]])
b=n.array([[[11,21,31]]])
print(n.stack((a,b),axis=3))

In [ ]:
#array joining
#a) v stack
#b) h stack
#c) coloumn stack
# in stacking convert array to its higher dimension

#v stack
# AXIS=O
a=n.array([1,2,3])
b=n.array([4,5,6])
print(n.vstack((a,b)))

In [ ]:
#2D
a=n.array([[1,2,3],[4,5,6]])
b=n.array([[4,5,6],[7,8,9]])
print(n.vstack((a,b)))

In [ ]:
#3D
a=n.array([[[1,2,3]],[[4,5,6]]])
b=n.array([[[8,5,6]],[[7,8,9]]])
print(n.vstack((a,b)))

In [ ]:
#h stack
#AXIS=1
a=n.array([[[11,21,31]],[[2,3,4]]])
b=n.array([[[41,51,61]],[[22,33,44]]])
print(n.hstack((a,b)))

In [ ]:
#2D
a=n.array([[11,21,31],[2,3,4]])
b=n.array([[41,51,61],[22,33,44]])
print(n.hstack((a,b)))

In [ ]:
# column stack
a=n.array([1,2,3])
b=n.array([4,5,6])
n.column_stack((a,b))

In [ ]:
#d stack
a=n.array([1,2,3])
b=n.array([4,5,6])
n.dstack((a,b))

In [ ]:
#2D
a=n.array([[11,21,31],[2,3,4]])
b=n.array([[41,51,61],[22,33,44]])
print(n.dstack((a,b)))

In [ ]:
#3D
a=n.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
b=n.array([[[8,5,6],[7,8,9]],[[101,111,112],[113,114,151]]])
print(n.dstack((a,b)))

In [ ]:
#spliting
a=n.arange(1,11)
n.split(a,5)

In [ ]:
a=n.arange(2,11)
n.split(a,[4]) # split array into 1st array as given numbers

In [ ]:
a=n.arange(1,11)
n.array_split(a,4) #split array into given numbers

In [ ]:
a=n.arange(1,7)
b=a.reshape(2,3)
print(b)
n.split(b,3,axis=1)

In [ ]:
a=n.arange(1,7)
b=a.reshape(2,3)
print(b)
n.split(b,[3],axis=1)

In [ ]:
a=n.arange(1,7)
b=a.reshape(2,3)
print(b)
n.array_split(b,3,axis=1)

In [ ]:
a=n.arange(1,7)
b=a.reshape(2,3,1)
n.array_split(b,3,axis=2)

In [ ]:
a=n.array([[[1,2,3],[3,4,5]],[[1,2,3],[2,3,4]]])
n.split(a,2,axis=1)

In [ ]:
a=n.array([[[1,2,3],[4,5,6]],[[10,11,12],[13,14,15]]])
n.split(a,[3],axis=2)

In [ ]:
#write a numpy prgrm to create (5,3,4)D array and split it into
#upto 2 based axis=1
#2s based axis=0
#4 equal parts based on axis-0
a=n.arange(1,61)
b=a.reshape(5,3,4)
print(b)
n.split(b,[2],axis=1)
n.array_split(b,2,axis=0)

In [ ]:
#h split 
#colomn wise spliting
a=n.array([[1,2,3,4],[5,6,7,8]])
n.hsplit(a,2)

In [ ]:
a=n.array([[[1,2,3,4],[5,6,7,8]],[[11,12,12,56],[89,13,14,15]]])
n.hsplit(a,2)

In [ ]:
a=n.arange(1,25).reshape(4,2,3)
print(a)
n.hsplit(a,2)
# row wise in 3d

In [ ]:
a=n.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
n.hsplit(a,2)

In [ ]:
#v split
a=n.arange(1,25).reshape(4,2,3)
print(a)
# b=n.hsplit(a,2)
# print(b)
a=n.arange(1,25).reshape(4,2,3)
n.vsplit(a,2)

In [ ]:
a=n.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
n.vsplit(a,3)

## where

In [ ]:
#where
a=n.arange(1,7)
print(a)
n.where(a==3)
n.where(a>3)
n.where(a%2==0)

In [ ]:
a=n.arange(1,13).reshape(2,3,2)
print(a)
n.where(a==3)

In [ ]:
#print index of odd numbers
a=n.arange(1,21)
print(a)
n.where(a%2!=0)

## search sorted

In [ ]:
a=n.arange(1,21)
n.searchsorted(a,1.5)

In [ ]:
a=n.array([6,2,1,5,6])
#a=n.sort(a)
n.searchsorted(a,1.5)

In [ ]:
a=n.array([3,1,5,4,2,6])
n.searchsorted(a,4.5)

In [ ]:
a=n.arange(1,21)
print(a)
n.searchsorted(a,[1.5,2.5,5.5])

In [ ]:
a=n.array([1,2,3,4,4,5,6,7])
n.searchsorted(a,4)

In [ ]:
a=n.array([1,2,3,4,4,5,6,7])
n.searchsorted(a,4,side='right')

In [ ]:
a=n.array([1,2,3,4,4,4,5,6,7])
n.searchsorted(a,4)

In [ ]:
a=n.array([1,2,3,4,4,4,5,6,7])
n.searchsorted(a,4,side='right')

## ARRAY FILTERING

In [ ]:
a=n.array([1,2,3])
b=[True,False,True]
a[b]

In [ ]:
a=n.arange(1,11)
b=[]
for i in a:
    if i%2==0:
       b.append(True)
    else:
        b.append(False)
a[b]

In [ ]:
a=n.arange(1,21).reshape(2,5,2)
a[a%2==0]

In [ ]:
a=n.arange(1,21)
b=[]
for i in a:
    if i>=10:
        b.append(True)
    else:
        b.append(False)
a[b]

In [ ]:
# in 2D
a=n.arange(1,11).reshape(2,5)
b=[]
for i in n.nditer(a):
    if 5<=i<=8:
        b.append(True)
    else:
        b.append(False)
a[n.array(b).reshape(2,5)]

In [ ]:
a=n.arange(1,21).reshape(2,5,2)
b=[]
for i in n.nditer(a):
    if i%2==0:
       b.append(True)
    else:
        b.append(False)
a[n.array(b).reshape(2,5,2)]

In [ ]:
a=n.arange(1,21).reshape(2,5,2)
print(a)
b=[]
for i in a:
    for j in i:
        for k in j:
            if k%2==0: 
                b.append(True)
            else:
                b.append(False)
print(n.array(b).reshape(2,5,2))
a[n.array(b).reshape(2,5,2)]

In [ ]:
# create a 2D numpy array,filter out and return the rows where the 2nd coloumn value is greater than 10
a=n.arange(1,21).reshape(4,5)
print(a)
b=[]
for i in a:
    if i[1]>10:
        b.append(i)
print(b)                  

In [ ]:
from numpy import random
a=n.random.randint(100,size=(4,4))
print(a)
b=[]
for i in a:
    if i[1]>50:
        b.append(i)
print(b)

In [2]:
# create a 2D numpy array,filter out and return the rows where the 2nd and 4th coloumn value is greater than 10
from numpy import random
import numpy as n
a=n.random.randint(100,size=(4,4))
print(a)
b=[]
for i in a:
    if i[1]>10 and i[3]>10:
        b.append(i)
print(b)

[[11 86 53 76]
 [65 71 94  4]
 [66 98 67 67]
 [99 20 89 60]]
[array([11, 86, 53, 76]), array([66, 98, 67, 67]), array([99, 20, 89, 60])]


In [ ]:
# create a 2D numpy array,filter out and return the coloumn where the 2nd and 4th row value is greater than 10
from numpy import random
a=n.random.randint(100,size=(4,4))
print(a)
count=0
b=[]
for i in a[1]:
    if i>=50:
        c=n.hsplit(a,4)
        b.append(c[count])
    count+=1
print(b)

In [ ]:
from numpy import random
a=n.random.randint(100,size=(4,4))
print(a)
c=n.hsplit(a,4)
b=[]
for i in c:
    if i[1]>=50:
        b.append(i)
print(b)

In [ ]:
from numpy import random
a=n.random.randint(50,size=(4,4))
print(a)
b=a.T
c=n.any(a<10,axis=0)
b[c]

In [ ]:
a=n.array([[1,2,3],[3,4,5]])
b=n.array([[5,6],[1,2],[4,5]])
print(n.matmul(a,b))
#number of coulm in 1st array and number of row in 2nd array should be equal

In [ ]:
a=n.arange(1,21).reshape(2,5,2)
print(a)
b=n.arange(1,21).reshape(2,2,5)
print(b)
print(n.matmul(a,b))

## view

In [ ]:
a=n.arange(1,11).reshape(2,5)
b=a.view()
#any change in view effect original array

In [ ]:
a=n.arange(1,11).reshape(2,5)
b=a.copy()
b[1]=10
c=a
c[1]=13
e=a.view()
e[1]=55
print(b)
print(e)
print(c)

In [ ]:
a=n.arange(1,11)
a.astype='bool'
print(a)

In [ ]:
#Write a Python program to iterate over a 3D NumPy array using ndenumerate and print each index and its corresponding value 
a=n.arange(1,11).reshape(2,5,1)
for i in n.ndenumerate(a):
    print(i)
#Write a Python function that counts the number of non-zero elements in a NumPy array using ndenumerate.
a=n.arange(0,10).reshape(2,5,1)
count=0
for i in n.nditer(a):
    if i!=0:
        count+=1
print(count)
#write a program to split [ [ [1,2] ],[ [3,4] ] ] array using hsplit ,vsplit 
a=n.array([[[1,2]],[[3,4]]])
n.hsplit(a,2)

In [ ]:
a=n.arange(1,11).reshape(2,5)
n.full_like(a,5)

In [ ]:
a=n.identity(6,dtype="int").reshape(1,6,6)
print(a)

In [ ]:
#create a identity matrix and chnage the diagnel elemenyts
a=n.identity(4,dtype="int")
for i in range (4):
    a[i,i]=i+1
a

a=n.identity(4,dtype="int")
b=0
for i in a:
    a[b,b]=b+1
    b+=1    
a
k=1
for i,j in n.ndenumerate(a):
   if(i[0]==i[1]):
        a[i]=k
        k+=1
print(a)


In [ ]:
#create a identity matrix and chnage the diagnel elements into even numbers
k=2
for i,j in n.ndenumerate(a):
   if(i[0]==i[1]):
        a[i]=k
        k+=2
print(a)

In [ ]:
a=n.arange(1,17).reshape(4,4)
for i,j in n.ndenumerate(a):
    if(i[0]==i[1]):
        a[i]=1
    else:
        a[i]=0
a

In [ ]:
#ading daignol element of 2 matrix
a=n.identity(4,dtype="int")
k=2
for i,j in n.ndenumerate(a):
   if(i[0]==i[1]):
        a[i]=k
        k+=2
b=n.identity(4,dtype="int")
x=1
for i,j in n.ndenumerate(b):
   if(i[0]==i[1]):
        b[i]=x
        x+=2
print(a+b)  

## ARRAY REPETITION

In [ ]:
a=n.array([1,2,3])
n.repeat(a,2,axis=0)

In [ ]:
a=n.array([[1,2,3]])
n.repeat(a,2,axis=0)

In [ ]:
a=n.arange(1,11).reshape(2,5)
print(a)
n.repeat(a,2,axis=0)

In [ ]:
a=n.arange(1,11).reshape(2,5)
print(a)
n.repeat(a,2,axis=1)

In [ ]:
a=n.arange(1,11).reshape(2,5,1)
print(a)
n.repeat(a,2,axis=2)

## numpy u function

In [ ]:
a=n.arange(1,11).reshape(2,5)
print(a)
print(n.cumproduct(a))
print(n.cumproduct(a,axis=0))
print(n.cumproduct(a,axis=1))

In [ ]:
a=n.arange(1,9).reshape(2,2,2)
print(a)
print(n.cumproduct(a,axis=0))
print(n.cumproduct(a,axis=1))
print(n.cumproduct(a,axis=2))

## DIFFRENCE

In [ ]:
a=n.array([2,3,4])
n.diff(a)

In [ ]:
a=n.array([2,3,4,11,6,9,8])
print(n.diff(a))
print(n.diff(a,n=2))

In [ ]:
a=n.arange(1,11).reshape(2,5)
print(a)
n.diff(a,axis=0)

In [ ]:
a=n.array([2,3,4,11,6,9,8])
n.log(a)

In [ ]:
import numpy
from numpy import matlib as mt
a=n.array([2,3,4,11,6,9,8])
mt.log(a)

## numpy Lcm

In [ ]:
import math
math.lcm(10,20,30)
math.lcm(11,12,13)

In [ ]:
a=n.array([2,3,4])
n.lcm.reduce(a)

In [ ]:
a=n.array([[1,4,6],[4,8,10]])
n.lcm.reduce(a)
n.gcd.reduce(a)

# creating our own u-function

In [ ]:
import numpy as np
def add(x,y):
    return x+y
a=np.frompyfunc(add,2,1)
# add(np.array([1,2,3]),np.array([2,3,4]))
a([1,2,3],[2,3,4])

In [ ]:
def moduls(a,b):
    return b%a
a=np.frompyfunc(moduls,2,1)
a([1,2,3],[4,5,6])

In [ ]:
# create a ufunc powr() to calculate power of elements of 2 array
# create au unfunc that check if one number is multiple of anathor
# create a ufunctn to find gcd&lcm
#create a ufuncnt to calcult temprature from celcius to farenheat
import numpy as np
def power(a,b):
    return a**b,b**a
a=np.frompyfunc(power,2,2)
a([2,3,4],[4,5,6])

a=np.array([2,3,4])
b=np.array([4,5,6])
def x(a,b):
    return  b%a==0
c=np.frompyfunc(x,2,1)
c(a,b)

a=np.array([2,3,4])
b=np.array([6,9,9])
def x(a,b):
    gcd=np.gcd(a,b)
    lcm=np.lcm(a,b)
    return gcd,lcm
c=np.frompyfunc(x,2,2)
c(a,b)

a=np.array([33,55,77])
def x(a):
    return (a*9/5)+32
c=np.frompyfunc(x,1,1)
c(a)

In [ ]:
#create a ufunct to calculate mean,median,mod
import numpy as n
a=n.array([33,55,77])
s=n.sum(a)
def mean(s):
    return s/3
c=n.frompyfunc(mean,1,1)
c(s)

In [ ]:
import numpy as n
def mean(x):
    return n.mean(a),n.median(a)
x=n.frompyfunc(mean, 1, 2)
a=n.array([33,55,77,55,56,78,78])
x(a[0])

## TRIGNOMETRY

In [ ]:
#find the sin value of 60
n.sin(60*(n.pi/180))
n.sin(n.deg2rad(60))


## numpy set operation

In [7]:
#create a set array in 1D 
a=n.array([2,3,4,5,3,6,7,4])
n.unique(a)
#finding union
a=n.array([2,3,4,5,6,7])
b=n.array([4,5,6,7,8,9])
n.union1d(a,b)
#finding intersection:- commen elements between 2 arrays
n.intersect1d(a,b,assume_unique=True)
a=n.array([1,1,2,4,5])
b=n.array([2,6,6])
n.intersect1d(a,b)
n.intersect1d(a,b,assume_unique=True)# only use when arrays are unique
# finding diffrence
a=n.array([2,3,4,5,6,7])
b=n.array([4,5,6,7,8,9])
n.setdiff1d(a,b)
a=n.array([1,1,2,4,5])
b=n.array([2,6,6])
n.setdiff1d(a,b,assume_unique=True)# only use when arrays are unique
#symmetric diffrence
a=n.array([2,3,4,5,6,7])
b=n.array([4,5,6,7,8,9])
n.setxor1d(a,b)
a=n.array([1,1,2,4,5])
b=n.array([2,6,6])
n.setxor1d(a,b,assume_unique=True)

array([4, 5])

In [ ]:
import numpy as n
#symmetric diffrence between 3 arrays
a=n.array([2,3,4,5,6,7])
b=n.array([4,5,6,7,8,9])
c=n.array([1,0,2,4,5,8])
print(n.setxor1d(n.setxor1d((a,b),c))
# find commen elements btween 3 arrays
k=n.array([2,3,4,5,6,7])
z=n.array([4,5,6,7,8,9])
y=n.array([1,0,2,4,5,8])
n.intersect1d(n.intersect1d(k,z),y)

In [9]:
# symmentric diffrence btwn empty arays
a=n.array([])
b=n.array([])
n.setxor1d(a,b)

array([], dtype=float64)

## random numbers in numpy

In [48]:
# program to write random numbers btween 10 to 100
# from numpy import random
n.random.randint(10,101,size=(4,5))
#program to create a random float number
import random
random.uniform(1,10) #to return float value
n.random.uniform(1,10,size=(4,5))
#print flot number between 0&1
random.random()# print float between 0&1
# write a program to create a set of random numbers of 3/2 matrics
n.random.randint(10,101,size=(2,5))

array([[ 17,  15,  32,  19,  64],
       [ 38,  92, 100,  84,  31]])

In [84]:
#create a set of random float numbers  of 3/2
n.random.uniform(1,10,size=(3,2))
#create a 3/2 matrix of float nmber between 0&1
n.random.uniform(0,1,size=(3,2))
n.random.rand(3,2)

array([[0.65298121, 0.15242385],
       [0.1594851 , 0.2223848 ],
       [0.06089999, 0.04187609]])

# random data distribution

In [2]:
#program to distribute numbers of 3,5,7,9 based on the corresponding probability .1,.3,.6,.0
n.random.choice([3,5,7,9],p=[.1,.3,.6,.0],size=(10,)) #sum of p should be 1
#probability of value of 3 is set to be .1 and correspondingly to others

# to create 2d array with 3rows and 5 coloums in which values of 3,5,7,8,9 should be as per p=[.2,.4,.1,.2,.1]
n.random.choice([3,5,7,8,9],p=[.2,.4,.1,.2,.1],size=(2,50))

array([[5, 7, 5, 5, 9, 9, 3, 5, 8, 5, 3, 5, 5, 5, 3, 3, 5, 5, 7, 8, 5, 5,
        3, 5, 3, 8, 5, 5, 5, 3, 7, 5, 5, 8, 8, 8, 3, 3, 8, 9, 8, 9, 9, 5,
        8, 5, 5, 8, 7, 7],
       [5, 9, 5, 5, 5, 8, 5, 9, 7, 5, 3, 9, 5, 8, 8, 8, 5, 9, 5, 3, 3, 5,
        5, 5, 8, 8, 3, 5, 3, 3, 9, 3, 3, 5, 3, 8, 5, 5, 5, 3, 5, 5, 5, 5,
        3, 8, 9, 5, 3, 7]])

## PERMUTATION

In [90]:
#SHUFLING
a=n.array([1,2,3,4])
n.random.shuffle(a)
a
#permutation
a=n.array([[1,2,3,4],[3,4,5,6]])
n.random.permutation(a)

#to shuffle a 2d array
a=n.array([[1,2,3,4],[3,4,5,6],[3,5,6,6]])
n.random.permutation(a.T).T
n.random.shuffle(a.T)
a
#IN 2D USING SHUFFLE METHOD WE CAN ARANGE ELEMENTS OF EACH ROWS IN DIFFRENT WAYS 

# TO SHUFFLE AN ARRAY OF STRINGS
a=n.array(['you','he','when','what','where'])
n.random.shuffle(a)
print(n.random.permutation(a))
a

['you' 'when' 'he' 'what' 'where']


array(['where', 'when', 'what', 'he', 'you'], dtype='<U5')

In [144]:
a='my name is anfas'
b=a.split(' ')
x=n.random.permutation(b)
z=' '.join(x)
print(z)
print(x)

anfas is my name
['anfas' 'is' 'my' 'name']


In [162]:
a='learn logic'
b=[]
for i in a:
    b.append(i)
n.random.shuffle(b)
print(''.join(b))
    

acnligol re


In [164]:
a='learn logic'
b=[ i for i in a]
print(b)
n.random.shuffle(b)
print(''.join(b))

['l', 'e', 'a', 'r', 'n', ' ', 'l', 'o', 'g', 'i', 'c']
gcr ainleol


In [179]:
# write a program to generate a random numbers in an array
print(n.random.randint(1,11,size=(2,5)))
print(n.random.uniform(1,11,size=(2,5)))
print(n.random.rand(2,5))
print(n.random.choice([i for i in range(1,100)],size=(2,5)))

[[ 6  8  8  1  2]
 [ 7 10  4  9  9]]
[[5.1792665  6.03449484 9.28575816 9.97267893 8.90745086]
 [8.09415766 1.31441464 2.54214404 2.23730518 5.02784616]]
[[0.28620889 0.76957904 0.42566314 0.34474307 0.58216307]
 [0.34754372 0.15619692 0.18873035 0.3639079  0.59184027]]
[[54 63  1  6 42]
 [ 5 42 83 67  4]]


In [16]:
a=n.arange(1,6)
print(a)
b=n.arange(6,11)
print(b)
def math(a,b):
    return n.add(a,b),n.subtract(a,b),n.multiply(a,b),n.divide(a,b),n.power(a,b),n.mod(b,a)
math(a,b)

[1 2 3 4 5]
[ 6  7  8  9 10]


(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]),
 array([      1,     128,    6561,  262144, 9765625], dtype=int32),
 array([0, 1, 2, 1, 0], dtype=int32))

In [18]:
a=n.arange(1,6)
b=n.arange(6,11)
def power(a,b):
    return n.power(a,b),n.mod(b,a)
x=n.frompyfunc(power,2,2)
x(a,b)

(array([1, 128, 6561, 262144, 9765625], dtype=object),
 array([0, 1, 2, 1, 0], dtype=object))

In [39]:
n.array([1,2,3,4,5]).reshape(5,1)
n.zeros(5)
n.ones(9)
n.empty(7)
n.arange(1,13).T
n.save('assigment.npy',a)
n.load('assigment.npy')
n.loadtxt('untitled.txt')

array(12345.)

In [7]:
a=n.arange(1,11)
b=n.arange(9,19)
def comp(a,b):
    return n.less(a,b),n.greater(a,b),n.less_equal(a,b),n.greater_equal(a,b)
x=n.frompyfunc(comp,2,4)
x(a,b)

(array([True, True, True, True, True, True, True, True, True, True],
       dtype=object),
 array([False, False, False, False, False, False, False, False, False,
        False], dtype=object),
 array([True, True, True, True, True, True, True, True, True, True],
       dtype=object),
 array([False, False, False, False, False, False, False, False, False,
        False], dtype=object))

In [75]:
# r=n.array([True,False,True,False])
# t=n.array([False,True,True,False])
# def comp(r,t):
#     return n.logical_and(r,t),n.logical_or(r,t),n.logical_not(r)
# x=n.frompyfunc(comp,2,3)
# x(r,t)

# i=n.array([0,1,2,3])
# o=n.array([1,2,3,4])
# def comp(h,j):
#     return n.logical_and(h,j),n.logical_or(h,j),n.logical_not(h,j)
# x=n.frompyfunc(comp,2,3)
# x(i,o)

i=n.array([0,1,2,3])
o=n.array([1,2,3,4])
print(n.logical_xor(i,o))

[ True False False False]


In [76]:
a=n.array(['and','odd'])
b=n.array(['you','is'])
def char(a,b):
    return n.char.add(a,b),n.char.multiply(a,2),n.char.upper(a),n.char.capitalize(a),n.char.join(a,b)
x=n.frompyfunc(char,2,5)
x(a,b)
a=n.array(['and','what'])
n.char.join('',a)

array(['and', 'what'], dtype='<U4')

In [7]:
a=n.array([[5,3,6,1]])
n.repeat(a,2,axis=0)

array([[5, 3, 6, 1],
       [5, 3, 6, 1]])

In [16]:
a=n.array([1,2,3])
n.repeat(a,4).reshape(2,6)
a=n.array([1,2,3])
n.tile(a,(2,2,2))

array([[[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]],

       [[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]])

In [17]:
a=n.array([9,5,1])
n.argsort(a)

array([2, 1, 0], dtype=int64)