In [13]:
import numpy as n
# a=n.arange(1,26).reshape(5,5)
# print(a)
# print(a[0:2,2:])

# a=n.arange(1,5).reshape(2,2)
# b=n.arange(5,9).reshape(2,2)
# print(a*b)

a=n.arange(1,7).reshape(2,3)
print(a)
b=n.array([1,2,3])
a+b

a=n.arange(1,7).reshape(2,3)
a.T

a=n.arange(1,7).reshape(2,3)
x=[i for i in n.nditer(a) if i>4]
x

a=n.array([[1,1,2,3,1],[2,4,2,3,2]])
n.unique(a,axis=1)

[[1 2 3]
 [4 5 6]]


array([[1, 1, 2, 3],
       [2, 4, 2, 3]])

In [29]:
import numpy as n
from numpy import random
a=random.randint(1,50,size=(5,2))
# a=[i for i in n.nditer(a) if i%2!=0]
for i,j in n.ndenumerate(a):
    if j%2!=0:
       a[i]=-1
print(a)


a=random.randint(1,10,size=(5,2))
b=random.randint(1,10,size=(5,2))
# x=[i for i in n.nditer()aif i==j]
print(n.intersect1d(a.flatten(),b.flatten()))

a=random.randint(1,10,size=(5,2))
print(n.sum(a))


[[32 -1]
 [ 4 22]
 [-1 -1]
 [46 12]
 [20 -1]]
[2 5 7 8 9]
49


In [44]:
a=n.ones(9).reshape(3,3)
a=a.astype(int)
a[::2,::2]=0
a[1,1::2]=0
print(a)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


In [74]:
a=n.ones(25).reshape(5,5)
a=a.astype(int)
a[1:-1,1:-1]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [92]:
a=n.array([1,2,3,4])
b=n.array([5,6,7,8])
n.concatenate((a,b))

a=n.array([[1,2,3,4]])
b=n.array([[5,6,7,8]])
n.concatenate((a,b),axis=1)

a=n.array([1,2,3,4])
b=n.array([5,6,7,8])
n.dstack((a,b))

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

In [95]:
a=random.randint(1,10,size=(5,2))
print(a)
print(n.sort(a,axis=0))
print(n.sort(a,axis=1))

a=random.randint(1,10,size=(5,2))
n.min(a)

[[6 3]
 [5 8]
 [3 4]
 [2 3]
 [3 2]]
[[2 2]
 [3 3]
 [3 3]
 [5 4]
 [6 8]]
[[3 6]
 [5 8]
 [3 4]
 [2 3]
 [2 3]]


In [103]:
a=n.array(['ard','you','and','who'])
n.sort(a)

array(['and', 'ard', 'who', 'you'], dtype='<U3')

In [122]:
a=random.randint(1,10,size=(10))
print(a)
b=n.arange(1,11)
print(b)
x=[i for i in b if i not in a]
x
# s=[]
# for i,j in n.nditer((a,b)):
#         if j not in a:
#             print(j)

[8 6 2 5 7 7 4 4 6 3]
[ 1  2  3  4  5  6  7  8  9 10]


[1, 9, 10]